### ISSUE TITLE
Example curl requests

### ISSUE THREAD

**Issue by tooptoop4** [merugu/springsecurity#1]
Hi

Can you include example curl requests for using this app in the readme?

Thanks

**Comment by merugu** [comment]
Hi, 
Download and start the app with "spring-boot:run" maven command and use the below curl request to generate JWT token
curl -d '{"username":"john", "password":"secret"}' -H "Content-Type: application/json" -X POST http://localhost:8085/api/auth/generatetoken

**Comment by tooptoop4** [comment]
would /api/auth/validatetoken endpoint be the one where u pass in authorization bearer and then do allow privileged responses?

**Comment by tooptoop4** [comment]
do u have example curl request for validatetoken?
