### ISSUE TITLE
How to make use ActiveDirectory server instead of ldif?

### ISSUE THREAD

**Issue by tooptoop4** [merugu/springsecurity#2]
How to make use ActiveDirectory server instead of ldif?

**Comment by merugu** [comment]
In this example I have used an embedded ldap server. To use your own active directory configure the below properties in application.yml 

app:
  jwtExpirationInMs: '604800000'
  jwtSecret: JWTSuperSecretKey
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
server:
  port: '8085'
spring:
  ldap:
    urls: ldap://yourcomapny:389/
    base: dc=yourcomapny,dc=com 
    username: cn=read-only-admin,dc=yourcomapny,dc=com
    password: password

And In SecurityConfig.java use something like below:

package com.innovativeintelli.ldapauthenticationjwttoken.config;

import java.util.Collections;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.security.authentication.AuthenticationManager;
import org.springframework.security.authentication.encoding.LdapShaPasswordEncoder;
import org.springframework.security.config.BeanIds;
import org.springframework.security.config.annotation.authentication.builders.AuthenticationManagerBuilder;
import org.springframework.security.config.annotation.method.configuration.EnableGlobalMethodSecurity;
import org.springframework.security.config.annotation.web.builders.HttpSecurity;
import org.springframework.security.config.annotation.web.configuration.EnableWebSecurity;
import org.springframework.security.config.annotation.web.configuration.WebSecurityConfigurerAdapter;
import org.springframework.security.ldap.DefaultSpringSecurityContextSource;

import com.innovativeintelli.ldapauthenticationjwttoken.security.JwtAuthenticationEntryPoint;

@Configuration
@EnableWebSecurity
@EnableGlobalMethodSecurity(
        securedEnabled = true,
        jsr250Enabled = true,
        prePostEnabled = true
)
public class SecurityConfig extends WebSecurityConfigurerAdapter {
	
	@Value("${spring.ldap.urls}")
	private String ldapUrls;
	
	@Value("${spring.ldap.base.dn}")
	private String ldapBaseDn;
	
	@Value("${spring.ldap.username}")
	private String ldapSecurityPrincipal;
	
	@Value("${spring.ldap.password}")
	private String ldapPrincipalPassword;
	
	
	  @Override
	    protected void configure(HttpSecurity http) throws Exception {
	        http
	        		.csrf()
	        			.disable()
	        		.cors()
	        			.disable()
	        		.exceptionHandling()
	        			.authenticationEntryPoint(unauthorizedHandler)
	        		.and()
	                .authorizeRequests()
	                    .antMatchers("/api/auth/**").permitAll()
	                    .anyRequest().authenticated();
	    }

	    @Override
	    public void configure(AuthenticationManagerBuilder auth) throws Exception {
	    	//Good to use BcryptEncoder for spring 5.0
	        auth
	                .ldapAuthentication()
	                    .userDnPatterns("uid={0},ou=people")
	                    .groupSearchBase("ou=groups")
	                .contextSource(contextSource())
	                .passwordCompare()
	                    .passwordEncoder(new LdapShaPasswordEncoder())
	                    .passwordAttribute("userPassword");
	    }
	    
	    

    @Autowired
    private JwtAuthenticationEntryPoint unauthorizedHandler;


    @Bean(BeanIds.AUTHENTICATION_MANAGER)
    @Override
    public AuthenticationManager authenticationManagerBean() throws Exception {
        return super.authenticationManagerBean();
    }

    @Bean
    public DefaultSpringSecurityContextSource contextSource() {
    	DefaultSpringSecurityContextSource defaultSpringSecurityContextSource=   new DefaultSpringSecurityContextSource(
                Collections.singletonList(ldapUrls), ldapBaseDn);
    	defaultSpringSecurityContextSource.setUserDn(ldapSecurityPrincipal);
    	defaultSpringSecurityContextSource.setPassword(ldapPrincipalPassword);
    	return defaultSpringSecurityContextSource;
    }
    
    
}

**Comment by tooptoop4** [comment]
what is this for? 

hibernate:
SQL: DEBUG
server:
port: '8085'

**Comment by merugu** [comment]
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG-- Is for logging SQL statement
server:
port: '8085' --Is the port number configured explicitly for restful service
